name: Tests
on: push
jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            diffutils

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run : |
          cmake -B build
          cmake --build build
      - name: Does the Executable Exist
        run: |
          ls 
          ls build
      - name: Check Output
        run: |
          ./build/lgcc.exe -i ./test/all > test/output.txt
      - name: check it?
        run: |
          cat test/output.txt
      - name: Tests
        run: |
          if ! cmp -s ./test/all.out ./test/output.txt; then
            echo "Test output differs from expected output."
            exit 1
          fi
