name: Tests
on: push
jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run : |
          cmake -B build
          cmake --build build
      - name: Does the Executable Exist
        run: |
          ls 
          ls build
      - name: Check Output
        run: |
          ./build/lgcc.exe -i ./test/all > test/output.txt
      - name: check it?
        run: |
          cat test/output.txt
      - name: Tests
        shell: powershell
        run: |
          ./build/lgcc.exe -i ./test/all | Out-File -FilePath "./test/output.txt" -Encoding ASCII
          if (-not (Test-Path "./test/output.txt")) {
            Write-Output "Error: Output file not found."
            exit 1
          }
          $outputContent = Get-Content -Path "./test/output.txt" -ErrorAction SilentlyContinue
          if (-not $outputContent) {
            Write-Output "Error: Output file is empty."
            exit 1
          }
          $expectedContent = Get-Content -Path "./test/all.out"
          if (-not $expectedContent) {
            Write-Output "Error: Expected output file not found."
            exit 1
          }
          if (-not ($outputContent -eq $expectedContent)) {
            Write-Output "Test output differs from expected output."
            exit 1
          }
