name: Tests
on: push
jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run : |
          cmake -B build
          cmake --build build

      - name: Tests
        shell: powershell
        run: |
          ./build/lgcc.exe -i ./test/all | Out-File -FilePath "./test/output.txt" -Encoding ASCII
          if (-not (Compare-Object -ReferenceObject (Get-Content -Path "./test/all.out") -DifferenceObject (Get-Content -Path "./test/output.txt")) -eq $null) {
            Write-Output "Test output differs from expected output."
            exit 1
          }